
/* This file is automatically generated from CBOR-diag files
 * or hex format files and should not be edited.
 */

#define EAT_TEST_USEFUL_BUF(test_name) ((struct q_useful_buf_c){test_name, sizeof(test_name)})


extern const unsigned char eat_test_completely_empty[1];


extern const unsigned char eat_test_some_submods[82];


extern const unsigned char eat_test_hw_version_invalid_board_version[12];


extern const unsigned char eat_test_hw_version_invalid_chip_version[17];


extern const unsigned char eat_test_hw_version_invalid_device_version[12];


extern const unsigned char eat_test_hw_version_invalid_ean_board_version[16];


extern const unsigned char eat_test_hw_version_invalid_version_scheme[15];


extern const unsigned char eat_test_hw_version_invalid_version_scheme_type[14];


extern const unsigned char eat_test_hw_version_invalid_version_scheme_value[16];


extern const unsigned char eat_test_hw_version_valid_board_version[14];


extern const unsigned char eat_test_hw_version_valid_chip_version[14];


extern const unsigned char eat_test_hw_version_valid_device_version[15];


extern const unsigned char eat_test_hw_version_valid_ean_board_version[22];


extern const unsigned char eat_test_hw_version_valid_ean_chip_version[22];


extern const unsigned char eat_test_hw_version_valid_ean_device_version[22];


extern const unsigned char eat_test_profile_invalid_type[3];


extern const unsigned char eat_test_profile_valid_oid[14];


extern const unsigned char eat_test_profile_valid_uri[28];


extern const unsigned char eat_test_psa_swcomponents_invalid_measurement_value[60];


extern const unsigned char eat_test_psa_swcomponents_invalid_missing_array[81];


extern const unsigned char eat_test_psa_swcomponents_invalid_no_and_claim[88];


extern const unsigned char eat_test_psa_swcomponents_invalid_no_measurement[77];


extern const unsigned char eat_test_psa_swcomponents_invalid_no_nor_claim[1];


extern const unsigned char eat_test_psa_swcomponents_invalid_no_signer_id[77];


extern const unsigned char eat_test_psa_swcomponents_invalid_no_type[7];


extern const unsigned char eat_test_psa_swcomponents_invalid_no_value[7];


extern const unsigned char eat_test_psa_swcomponents_invalid_signer_id[50];


extern const unsigned char eat_test_psa_swcomponents_valid_basic[187];


extern const unsigned char eat_test_psa_swcomponents_valid_no[7];


extern const unsigned char eat_test_secboot_invalid1[3];


extern const unsigned char eat_test_secboot_invalid2[3];


extern const unsigned char eat_test_secboot_invalid4[8];


extern const unsigned char eat_test_secboot_invalid5[7];


extern const unsigned char eat_test_secboot_valid1[3];


extern const unsigned char eat_test_secboot_valid2[3];


extern const unsigned char eat_test_submods_invalid_is_array[19];


extern const unsigned char eat_test_submods_invalid_non_string_label[28];


extern const unsigned char eat_test_submods_valid_deeply_nested[130];


extern const unsigned char eat_test_submods_valid_empty[11];


extern const unsigned char eat_test_submods_valid_minimal[40];


extern const unsigned char eat_test_hw_version_invalid_nwf[7];


extern const unsigned char eat_test_profile_invalid_dup[23];


extern const unsigned char eat_test_profile_invalid_nwf[3];


extern const unsigned char eat_test_psa_swcomponents_invalid_nwf_signer_id[50];


extern const unsigned char eat_test_psa_swcomponents_invalid_nwf_swc[7];


extern const unsigned char eat_test_secboot_invalid3[3];


extern const unsigned char eat_test_submods_invalid_duplicate[73];


extern const unsigned char eat_test_submods_invalid_nwf_section[3];


extern const unsigned char eat_test_submods_invalid_nwf_sumbod[11];


